### ISSUE TITLE
How to ensure that the output of the encoder is independent of the speaker？

### ISSUE THREAD

**Issue by hyzhan** [auspicious3000/autovc#3]
How to ensure that the output of the encoder is independent of the speaker？
I can't see the concept of confusing networks or generative adversarial training in this paper.
I don't understand how it works.

**Comment by auspicious3000** [comment]
As the title "AutoVC: Zero-Shot Voice Style Transfer with Only Autoencoder Loss" indicates, the main idea of the paper is to get rid of adversarial loss, instead of using it.

**Comment by nkcdy** [comment]
> How to ensure that the output of the encoder is independent of the speaker？
> I can't see the concept of confusing networks or generative adversarial training in this paper.
> I don't understand how it works.

My guess is in training stage, the network uses only the reconstruction loss. That means if the output of the network match the input of the network perfectly, the network will FORCE the output of the encoder to be independent of the speaker because the speaker embedding has already been fed in through another path. Something like feedback theory.
